# Site settings
name: name
email: email
url: url
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /testjekyll

# social
github:
  username: jeffreyallen92

twitter:
  username: boomiFGC
